# Generated by Django 5.2.7 on 2025-11-04 18:47

import django.core.validators
import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('titulo', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ano_lancamento', models.IntegerField(blank=True, db_index=True, null=True)),
                ('duracao_min', models.IntegerField(blank=True, null=True, verbose_name='Duração (minutos)')),
                ('classificacao', models.CharField(blank=True, help_text="Ex.: 'M/14', 'PG-13', 'R'", max_length=10, verbose_name='Classificação etária')),
                ('poster_url', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('popularidade', models.FloatField(db_index=True, default=0.0)),
                ('media_rating', models.FloatField(db_index=True, default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='filmes', to='core.etiqueta')),
            ],
            options={
                'ordering': ['-popularidade', '-media_rating', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('papel', models.CharField(choices=[('ator', 'Ator/Atriz'), ('realizador', 'Realizador'), ('roteirista', 'Roteirista'), ('produtor', 'Produtor'), ('compositor', 'Compositor'), ('outro', 'Outro')], default='ator', max_length=20)),
                ('personagem', models.CharField(blank=True, max_length=120)),
                ('ordem_credito', models.PositiveIntegerField(db_index=True, default=0)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='core.filme')),
            ],
            options={
                'ordering': ['filme', 'ordem_credito', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='core_genero_nome_7a627e_idx'), models.Index(fields=['slug'], name='core_genero_slug_c5ed25_idx')],
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(blank=True, related_name='filmes', to='core.genero'),
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='ISO-639-1')),
            ],
            options={
                'verbose_name': 'Língua',
                'verbose_name_plural': 'Línguas',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['codigo'], name='core_lingua_codigo_abf624_idx')],
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='linguas',
            field=models.ManyToManyField(blank=True, related_name='filmes', to='core.lingua'),
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('iso2', models.CharField(max_length=2, unique=True, verbose_name='ISO-3166-1 alpha-2')),
            ],
            options={
                'verbose_name_plural': 'Países',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['iso2'], name='core_pais_iso2_38332c_idx')],
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='paises',
            field=models.ManyToManyField(blank=True, related_name='filmes', to='core.pais'),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('nome', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='core_pessoa_nome_124496_idx')],
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='elenco',
            field=models.ManyToManyField(blank=True, related_name='filmes_participados', through='core.Elenco', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='elenco',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='core.pessoa'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(db_index=True, help_text='0 a 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.filme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tipo', models.CharField(choices=[('trailer', 'Trailer'), ('teaser', 'Teaser'), ('clip', 'Clip'), ('outro', 'Outro')], default='trailer', max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('fonte', models.CharField(blank=True, max_length=50)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.filme')),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lingua')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('marcado_em', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_watchlists', to='core.filme')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-marcado_em'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('marcado_em', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='core.filme')),
            ],
            options={
                'ordering': ['-marcado_em'],
                'indexes': [models.Index(fields=['utilizador'], name='core_favori_utiliza_a66691_idx'), models.Index(fields=['filme'], name='core_favori_filme_i_007414_idx')],
                'unique_together': {('utilizador', 'filme')},
            },
        ),
        migrations.AddIndex(
            model_name='filme',
            index=models.Index(fields=['titulo'], name='core_filme_titulo_bc3c27_idx'),
        ),
        migrations.AddIndex(
            model_name='filme',
            index=models.Index(fields=['ano_lancamento'], name='core_filme_ano_lan_343ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='filme',
            index=models.Index(fields=['-popularidade', '-media_rating'], name='core_filme_popular_742be9_idx'),
        ),
        migrations.AddConstraint(
            model_name='filme',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('titulo', 'ano_lancamento'), name='uniq_titulo_ano'),
        ),
        migrations.AddIndex(
            model_name='elenco',
            index=models.Index(fields=['filme', 'papel'], name='core_elenco_filme_i_aeafc9_idx'),
        ),
        migrations.AddIndex(
            model_name='elenco',
            index=models.Index(fields=['pessoa', 'papel'], name='core_elenco_pessoa__189270_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='elenco',
            unique_together={('filme', 'pessoa', 'papel', 'personagem')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['filme', '-created_at'], name='core_review_filme_i_61e661_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['autor', '-created_at'], name='core_review_autor_i_0c2d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['filme', 'rating'], name='core_review_filme_i_cc6737_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('filme', 'autor')},
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['tipo'], name='core_video_tipo_640c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['filme', 'tipo'], name='core_video_filme_i_3adad0_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['utilizador'], name='core_watchl_utiliza_c4b628_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['filme'], name='core_watchl_filme_i_8823e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('utilizador', 'filme')},
        ),
    ]
